# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4072dfbbfe4992b68ae66501060d0b08aa2c8b0cc6cba6d148fe5a243cbc63df853fa5bf6f08b8e27fbbcf37ac07b5cedbe28accc9a82ba0e07533f7bef61789

test:
  secret_key_base: 82a2ca411a73e0fc53545e97aebdf0d168195bc77a15cd51d73c9a95cc71c409d19a20cb0efd5ff31fc329d0931ad304a9f4eaadef958a89cd36d8a81d35c282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
